name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🌟 Enhancements'
    labels:
      - 'enhancement'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
  - title: '⚡ Performance'
    labels:
      - 'performance'



change-template: |
  - $TITLE (#$NUMBER) by @$AUTHOR
   


template: |
  ## What's new here today!

  $CHANGES

   {{ range .Categories }}
  ### {{ .Title }}

  {{ range .Changes }}
  {{ . }}
  {{ end }}
  {{ end }}

  ## Contributors
  {{ range .Contributors }}
  - @{{ . }}
  {{ end }}
